name: Packages - Upload WPK images
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name of the Docker image to be uploaded (Use developer to set branch name. Use auto to set src/VERSION content)'
        required: false
        default: auto
jobs:
  Upload-WPK-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - CONTAINER_NAME: linux_wpk_builder_x86_64
            DOCKERFILE_PATH: packages/wpk/linux/x86_64
          - CONTAINER_NAME: common_wpk_builder
            DOCKERFILE_PATH: packages/wpk/common
      fail-fast: false
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - uses: actions/checkout@v4

      - name: Copy scripts to Dockerfile path
        run: |
          cp $GITHUB_WORKSPACE/packages/wpk/run.sh $GITHUB_WORKSPACE/${{ matrix.DOCKERFILE_PATH }}
          cp $GITHUB_WORKSPACE/packages/wpk/wpkpack.py $GITHUB_WORKSPACE/${{ matrix.DOCKERFILE_PATH }}

      - name: Set tag
        run: |
          VERSION=$(sed 's/v\([0-9]*\.[0-9]*\.[0-9]*\)/\1/' $GITHUB_WORKSPACE/src/VERSION)
          if [ "${{ github.event.inputs.tag }}" == "auto" ]; then echo "TAG=$VERSION" >> $GITHUB_ENV;
          elif [ "${{ github.event.inputs.tag }}" == "developer" ]; then echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV;
          else echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV; fi

      - name: Build and push image ${{ matrix.CONTAINER_NAME }} with tag ${{ env.TAG }} to Github Container Registry
        run:
          bash $GITHUB_WORKSPACE/.github/actions/ghcr-pull-and-push/build_and_push_image_to_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} ${{matrix.CONTAINER_NAME}} ${{ matrix.DOCKERFILE_PATH }} ${{ env.TAG }}
